config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users do
  resources :bookings, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :bookings, except: [:new, :create]


  patch '/approve', to: 'bookings#approve', as: 'approve'
  patch '/reject', to: 'bookings#reject', as: 'reject'


  get '/uikit', to: 'pages#design'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: "User"
  belongs_to :plant_sitter, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings_by_customer, class_name: 'Booking', foreign_key: :customer_id
  has_many :bookings_by_plant_sitter, class_name: 'Booking', foreign_key: :plant_sitter_id
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @plant_sitter = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.plant_sitter = User.find(params[:user_id])
    @booking.customer = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def index
    @bookings = Booking.all
    @bookings.each do |booking|
      booking.status
    end
  end

  def show
    @booking = Booking.find(params[:id])
    # if @booking.status = true
    #   @booking.status = "Accepted"
    # end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end


  def approve
    @booking = Booking.find(params[:id])
    @booking.status = true
    @booking.save
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = false
    @booking.save
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :customer_id, :plant_sitter_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def design
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :postal_code, :bio, :plant_sitter, :pick_up, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_card.html.erb
<% if current_user.plant_sitter? %>
  <div class="card-product">
    <%= cl_image_tag booking.customer.photo.key,
    crop: :thumb, gravity: :face %>
    <div class="card-product-infos">
      <!-- using bootstrap to display next to eachother -->
      <div class="d-flex justify-content-between">

        <h2><%= "#{booking.customer.first_name} #{booking.customer.last_name}" %></h2>
        <div class="d-flex">
          <!-- approved & rejected buttons -->
          <!-- approve -->
          <%= link_to '<i class="fa fa-check" aria-hidden="true"></i>'.html_safe, approve_path(id: booking.id), method: :patch %>
          <!-- reject -->
          <%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, reject_path(id: booking.id), method: :patch %>
        </div>
      </div>

      <p> <%= "#{booking.start_date} - #{booking.end_date}" %></p>
      <% if booking.status == true %>
        <p>Approved</p>
      <% elsif booking.status == false %>
        <p>Rejected</p>
      <% else %>
        <p>Pending</p>
      <% end %>

      <div class="card-link">
        <%= link_to 'BOOKING DETAILS', booking_path(booking) %>
      </div>

    </div>
  </div>


<% else %>


  <div class="card-product">
    <%= cl_image_tag booking.plant_sitter.photo.key,
    crop: :thumb, gravity: :face %>

    <div class="card-product-infos">
      <div>
        <h2><%= "#{booking.plant_sitter.first_name} #{booking.plant_sitter.last_name}" %></h2>
        <p> <%= "#{booking.start_date} - #{booking.end_date}" %></p>

        <% if booking.status == true %>
          <p>Approved</p>
        <% elsif booking.status == false %>
          <p>Rejected</p>
        <% else %>
          <p>Pending</p>
        <% end %>
      </div>

      <div>
        <%= link_to 'Booking details', booking_path(booking) %>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1 class="mobile-header"> My Plant-Sitting Requests</h1>

<div class="card-container">
  <% if current_user.plant_sitter == true %>
    <% @bookings.where(plant_sitter_id: current_user.id).each do |booking| %>
      <%= render 'booking_card', {booking: booking} %>
    <% end %>
  <% else %>
    <% @bookings.where(customer_id: current_user.id).each do |booking| %>
      <%= render 'booking_card', {booking: booking} %>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Confirm booking details</h1>
<div class="user-show-card">
  <p>Your plantsitter is <strong><%= @plant_sitter.first_name %> <%= @plant_sitter.last_name %></strong></p>

  <%= simple_form_for @booking, url: user_bookings_path(@plant_sitter), method: :post do |t| %>
    <%= t.input :start_date, as: :date %>
    <%= t.input :end_date, as: :date %>
    <div class="btn-purple"><%= t.button :submit %></div>
  <% end %>
  <br>
  <!-- <a href="/bookings">Go back to bookings</a> -->
  <div>
     <%= link_to "Go back to plantsitters", users_path, class: "btn-purple" %>
  </div>
  <br>
</div>

app/views/bookings/show.html.erb
<h1> Booking Confirmation</h1>

<div class="user-show-card">
    <br>
      <p>Thank you for booking with PlantSitter, <%= "#{User.find(@booking.customer_id).first_name}"%>! Below are your booking details:</p>
      <p> <strong>Plant Sitter:</strong>  <%= "#{User.find(@booking.plant_sitter_id).first_name} #{User.find(@booking.plant_sitter_id).last_name}" %></p>
      <p> <strong> Booking start date:</strong> <%= @booking.start_date %></p>
      <p> <strong>Booking end date:</strong> <%= @booking.end_date %></p>
      <p> <strong>Price:</strong> $<%=User.find(@booking.plant_sitter_id).price %> per day</p>

    <% if @booking.status == true %>
      <p>Booking status: Approved</p>
    <% elsif @booking.status == false %>
      <p>Booking status: Rejected</p>
    <% else %>
      <p><strong>  Booking status:</strong>  <strong> <em> Pending.</em></strong> Once the booking is approved by your plant sitter, you will receive a notification by email!</p>
    <% end %>
    <br>
    <div>
      <%= link_to "Go back to my bookings", bookings_path, class: "btn-purple" %>
    </div>
    <br>
    <div>
      <%= link_to "Go back to plantsitters", users_path, class: "btn-purple" %>
    </div>
    <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantsitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/pages/_home.scss">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/design.html.erb
<!-- # <%= link_to 'Booking', booking_path(booking) %> Start date: <%=booking.start_date%> End date: <%=booking.end_date%> Status: <%=booking.status%>

# // Background for all except home page

# <div style="background: url(<%= asset_path "fern.jpeg" %>)">
 -->

app/views/pages/home.html.erb
<!-- <img src="/app/assets/images/monstera.jpeg" alt=""> -->
<div style="background: url(<%= asset_path "monstera.jpg" %>)">
  <div class="home-container">
    <div class="d-flex justify-content-center text-align-center">
      <h1>What would you like to do today?</h1>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "FIND A PLANT SITTER", users_path, class:"btn-medium-gold" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "MANAGE MY BOOKINGS", bookings_path, class:"btn-medium-gold" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fa fa-leaf" aria-hidden="true"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">

          <% if user_signed_in? %>
            <%= cl_image_tag current_user.photo.key, height: 200, width: 200, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup' => true, 'aria-expanded' => false %>
          <% else %>
             <%= cl_image_tag "staff-avatar-man_alxhsy", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup' => true, 'aria-expanded' => false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "See my bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_user_card.html.erb
<div class="user_card">

  <div class="user_card_action">
    <%= cl_image_tag(user.photo.key, crop: :thumb, gravity: :face) %>
  </div>

  <div class="user_card_info">
    <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
    <p><%= user.postal_code %></p>
    <p>$<%= user.price %></p>
    <div>
      <%= link_to "learn more", user_path(user), class: "btn-purple" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<section class="section">
  <div style="background: url(<%= asset_path "fern.jpg" %>)">
    <div class="container">
      <h1>Plant Sitters in your area</h1>
      <div class="all-users">
        <% @users.each do |user| %>
          <% if user.plant_sitter == true %>
            <%= render 'user_card', {user: user} %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>


<!-- <img src="/app/assets/images/monstera.jpeg" alt=""> -->


<!-- <div class="d-flex justify-content-center">
      <a class="btn-medium-gold" href="">plant sitter</a>
    </div> -->

app/views/users/show.html.erb
<div class="user-show-card">
  <%= cl_image_tag(@user.photo.key,
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

  <div class="info-box">
    <p><strong><%= @user.first_name %> <%= @user.last_name %></strong></p>
    <p><strong>E-mail: </strong><%= @user.email %></p>
    <p><strong>Postal code: </strong><%= @user.postal_code %></p>
    <p><strong>Bio: </strong><%= @user.bio %></p>
    <p><strong><%= @user.pick_up ? "#{@user.first_name} can do pick-up!" : "#{@user.first_name} doesn't offer pick-up" %></strong></p>
    <p><strong>Price: </strong>$<%= @user.price %></p>
    <p><%= link_to "Book me!",  new_user_booking_path(@user.id) %></p>
    <p><%= link_to "List of PlantSitters",  users_path %></p>
  </div>

</div>